import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Taka-App",
  description: "Taka is a Swahili word meaning garbage. Taka-App is an AI-powered waste management platform that aims to reduce the amount of waste generated by the modern society.",
}